const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUpView";
const String HomeViewRoute = "HomeView";
const String ClientMainViewRoute = "ClientMainView";
const String CreateDeliveryViewRoute = "CreateDeliveryView";
const String CreateStartViewRoute = "CreateStartView";
const String CreateEndViewRoute = "CreateEndView";
const String CreateObjectViewRoute = "CreateObjectView";
const String ConfirmLocationViewRoute = "ConfirmLocationView";
const String DeliveryViewRoute = "DeliveryView";
const String DeliveryMapViewRoute = "DeliveryMapView";
const String ClientViewRoute = "ClientView";
const String ConfigViewRoute = "ConfigView";
const String AddFavoritesViewRoute = "AddFavoritesView";
// Generate the views here